services:
  postgresdb:
    image: postgres:latest
    container_name: postsdb
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=posts
    networks:
      - app-network
  mysqldb:
    image: mysql
    container_name: friendsdb
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=friends_db
      - MYSQL_USER=rafik
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=password
    networks:
      - app-network
  mongodb:
    image: mongo:7.0.5
    container_name: chatsdb
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: password
       MONGO_INITDB0_DATABASE: chats_db
    networks:
      - app-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - app-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - app-network
  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - app-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
      - "--import-realm"
    restart: unless-stopped
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro
    networks:
      - app-network
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - 8888:8888
    networks:
      - app-network
  eureka:
    container_name: eureka
    build:
      context: ./eureka
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      - app-network
  gateway:
    container_name: gateway
    build:
      context: ./api-gateway
    ports:
      - 8222:8222
    depends_on:
      - keycloak
      - eureka
    networks:
      - app-network
  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - 8030:8030
    depends_on:
      - gateway
      - keycloak
    networks:
      - app-network
  post-service:
    container_name: post-service
    build:
      context: ./post-service
    ports:
      - 8040:8040
    depends_on:
      - gateway
      - postgresdb
      - kafka
    networks:
      - app-network
  friends-service:
    container_name: friends-service
    build:
      context: ./friends-service
    ports:
      - 8050:8050
    depends_on:
      - gateway
      - mysqldb
      - kafka
    networks:
      - app-network
  chat-service:
    container_name: chat-service
    build:
      context: ./chat-service
    ports:
      - 8060:8060
    depends_on:
      - gateway
      - mongodb
    networks:
      - app-network
  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
    ports:
      - 8010:8010
    depends_on:
      - gateway
      - kafka
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
