eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test1
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: chats-ws
          uri: http://localhost:8060
          predicates:
            - Path=/ws-demo/**
        - id: user-service
          uri: http://localhost:8030
          predicates:
              - Path=/api/v1/users/**
        - id: post-service
          uri: http://localhost:8040
          predicates:
              - Path=/api/v1/posts/**
        - id: post-uploads
          uri: http://localhost:8040
          predicates:
            - Path=/uploads/posts/**
          filters:
            - RewritePath=/uploads/posts/(?<remaining>.*), /uploads/${remaining}
        - id: friends-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/friends/**
      discovery:
        locator:
          enabled: true
