eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
