spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/chatsdb?authSource=admin
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8060