server:
  port: 8010
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: friendRequest:com.example.notification_service.events.FriendRequestEvent,commentRequest:com.example.notification_service.events.NewCommentEvent
  mail:
    host: mail-dev
    port: 1025
    username: rafik
    password: ben
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
