spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/posts
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

  application:
    name: post-service
server:
  port: 8040
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
