export const BASE_API_URL = "http://localhost:8222/api/v1";


export const INTERESTS = [
    "Technology",
    "Travel",
    "Fitness",
    "Music",
    "Movies",
    "Art",
    "Photography",
    "Fashion",
    "Sports",
    "Books",
    "Cooking",
    "Gaming",
    "Nature",
    "Animals",
    "Health",
    "Science",
    "DIY",
    "Cars",
    "History",
    "Politics",
    "Writing",
    "Reading",
    "Food",
    "Languages",
    "Dance",
    "Yoga",
    "Meditation",
    "Cycling",
    "Running",
    "Hiking",
    "Swimming",
    "Skating",
    "Chess",
    "Board Games",
    "Gardening",
    "Fishing",
    "Volunteering",
    "Startups",
    "Investment",
    "Coding",
    "Podcasting",
    "Blogging"
  ];