spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888 
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
